project:
  type: website
  output-dir: docs

website:
  title: "Shreekari Maruvada"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: data story.qmd
        text: Data Story
      - href: analysis.qmd
        text: Analysis of Data
      - href: conclusion.qmd
        text: Conclusion
      - href: reflections.qmd
        text: Reflections

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

